name: recepia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  feature_folder_cli: ^0.3.0
  dio: ^5.4.0
  provider: ^6.1.1
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.2.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/food/
